### ISSUE TITLE
prov navigation slightly off

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#402] opened 2017-11-28 20:02 UTC
When navigating from a prov icon, the location on the page is slightly below
the top of the package member detail section, such that the user has to
scroll up to see where they are. Here is a view after navigating to "plot_radargram.m":

<img width="1125" alt="screen shot 2017-11-28 at 11 56 35 am" src="https://user-images.githubusercontent.com/6412946/33341430-d633ce0e-d433-11e7-937c-bd824e98916c.png">

This is seen in package https://beta.arcticdata.io/catalog/#view/doi:10.18739/A2JK2R

**Comment by laurenwalker** [comment] 2017-11-28 20:08
This is a duplicate of #383

**Closed by laurenwalker** 2017-11-28 20:08 UTC
Labels: bug, provenance
