### ISSUE TITLE
Negated operators don't always give the expected results in the Query Builder

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1600] opened 2020-11-04 22:41 UTC
The operators `does not equal`, `does not contain`, and `is empty` all set the Filter model attribute `exclude` to `true`. When exclude is true, the Solr query string for that filter includes a `-` sign before the associated query. If a portal comprises just one query rule, and that rule uses one of these "negated" operators, then the data search gives 0 results. If a second rule is added using any of the _other_ operators, then there are >0 results. A few examples:

---

#### A: Just one rule

<img width="1370" alt="Screen Shot 2020-11-04 at 16 42 56" src="https://user-images.githubusercontent.com/26600641/98173899-e71eaa00-1ec1-11eb-9c15-bdef48cff405.png">

- **Query:** [`((-title:"Lake Level for Harlequin Lake 2009-2011")) AND (-obsoletedBy:* AND formatType:METADATA)`](https://search.dataone.org/cn/v2/query/solr/?q=((-title:%22Lake%20Level%20for%20Harlequin%20Lake%202009-2011%22))%20AND%20(-obsoletedBy:*%20AND%20formatType:METADATA)&fl=id)
- **Number of results: 0**

#### B: Multiple rules

<img width="1370" alt="Screen Shot 2020-11-04 at 16 43 35" src="https://user-images.githubusercontent.com/26600641/98173942-fd2c6a80-1ec1-11eb-8ffe-aff2e8a832b7.png">

- **Query:** [`((-title:"Lake Level for Harlequin Lake 2009-2011" AND abstract:*)) AND (-obsoletedBy:* AND formatType:METADATA)`](https://search.dataone.org/cn/v2/query/solr/?q=((-title:%22Lake%20Level%20for%20Harlequin%20Lake%202009-2011%22%20AND%20abstract:*))%20AND%20(-obsoletedBy:*%20AND%20formatType:METADATA)&fl=id)
- **Number of results: 413,759**

---

#### A: Just one rule

<img width="1370" alt="Screen Shot 2020-11-04 at 16 55 14" src="https://user-images.githubusercontent.com/26600641/98174131-5e543e00-1ec2-11eb-8af3-62c215e20ebb.png">

- **Query:** [`((-projectText:*)) AND (-obsoletedBy:* AND formatType:METADATA)`](https://search.dataone.org/cn/v2/query/solr/?q=((-projectText:*))%20AND%20(-obsoletedBy:*%20AND%20formatType:METADATA)&fl=id)
- **Number of results: 0**

#### B: Multiple rules

<img width="1370" alt="Screen Shot 2020-11-04 at 16 59 59" src="https://user-images.githubusercontent.com/26600641/98174156-690ed300-1ec2-11eb-9824-3a9f911ae454.png">

- **Query:** [`((-projectText:* AND text:*)) AND (-obsoletedBy:* AND formatType:METADATA)`](https://search.dataone.org/cn/v2/query/solr/?q=((-projectText:*%20AND%20text:*))%20AND%20(-obsoletedBy:*%20AND%20formatType:METADATA)&fl=id)
- **Number of results: 757,090**

---

#### A: Just one rule

<img width="1370" alt="Screen Shot 2020-11-04 at 17 05 29" src="https://user-images.githubusercontent.com/26600641/98174344-bd19b780-1ec2-11eb-9a86-6ff23ede96ad.png">

- **Query:** [`((-abstract:*fish*)) AND (-obsoletedBy:* AND formatType:METADATA)`](https://search.dataone.org/cn/v2/query/solr/?q=((-abstract:*fish*))%20AND%20(-obsoletedBy:*%20AND%20formatType:METADATA)&fl=id)
- **Number of results: 0**

#### B: Multiple rules

<img width="1370" alt="Screen Shot 2020-11-04 at 17 06 52" src="https://user-images.githubusercontent.com/26600641/98174354-c2770200-1ec2-11eb-9359-67ce30c29dbc.png">

- **Query:** [`((-abstract:*fish* AND text:*)) AND (-obsoletedBy:* AND formatType:METADATA)`](https://search.dataone.org/cn/v2/query/solr/?q=((-abstract:*fish*%20AND%20text:*))%20AND%20(-obsoletedBy:*%20AND%20formatType:METADATA)&fl=id)
- **Number of results: 805,260**

---

**To Reproduce**
Build queries like the examples above

**Expected behavior**
I would expect that a single rule with a negated operator should give all the results that don't match the given value. In example 3A, for instance, I would expect to find *all* the datasets where the abstract doesn't contain the word "fish".

A possible solution could be to build the queries in a special way for Filter model that have `exclude` set to `true`. The rule could be ANDed together with another rule such as `text:*`. For example 3A, instead of `-abstract:*fish*`, the query could be `(-abstract:*fish* AND text:*)`

**Comment by gothub** [comment] 2021-01-12 22:36
@robyngit yeah, this is unexpected behavior for Solr, nice catch!

I found this [helpful post](https://cwiki.apache.org/confluence/display/SOLR/NegativeQueryProblems) that proposes a couple of solutions:
- the query processor can give the correct results if the first negative term doesn't have parens around it (???)
- add a positive result clause that the 'negative' clause can subtract from (which you proposed to fix example 3A), but uses the term `*:*` instead of `text:*`. Maybe `text:*` is less work for Solr.

I'll have to check for this same condition when building the 'collectionQuery' solr field from the search filter `<definition>`.

**Comment by amoeba** [comment] 2021-01-13 00:04
Looks like all of these 0-result queries can be fixed by removing all parens. Maybe this is because, as @gothub [link](https://cwiki.apache.org/confluence/display/SOLR/NegativeQueryProblems) points out, Solr can self-rescue. Might also be because `formatType:METADATA+AND+-obsoletedBy:*` returns the "full" set of docs we want to filter on in the first place.

If we change MetacatUI to not wrap everything in parens, do we get the expected result in the above cases? It's not clear to me why MetacatUI uses parens in any of the above situations.

Also as a note: The fixed versions of the queries above where extra filter terms like `abstract:*` get added do not give what I'd call the right result because it filters to documents that have abstracts which is not exactly what the user intended. I think all examples would be better with `*:*` added instead of anything else.

**Comment by robyngit** [comment] 2021-01-13 19:39
This is a *very* helpful article, thanks @gothub! It's nice to understand why we see this behaviour.

> If we change MetacatUI to not wrap everything in parens, do we get the expected result in the above cases? It's not clear to me why MetacatUI uses parens in any of the above situations.

True that the parentheses aren't needed in these examples, but I think they will be important when it comes to more complex queries, especially when we start supporting filter groups in the Query Builder.

I think the simplest solution is just to append ` AND *:*` to any query string that is built from a Filter model that's negative (`exclude:true`).

So line 305 ...

https://github.com/NCEAS/metacatui/blob/3bdc66d662d68bc438a0552146c7f8adb02e52fa/src/js/models/filters/Filter.js#L304-L306

Would just become ...

```js
queryString = "-" + queryString + "%20AND%20*:*"
```
Seems to fix all the issues in the first comment.

**Closed** 2021-01-27 20:47 UTC
Labels: Portal Editor, bug, portals, query builder
