### ISSUE TITLE
Editor testing: Unable to submit package when entering only required fields  (IE, Windows)

### ISSUE THREAD

**Issue by veeveetran** [NCEAS/metacatui#553] opened 2018-04-03 20:15 UTC
Using IE 11 on Windows 7 Enterprise.

I am trying to submit a test package by entering only the required fields:
- Title
- Abstract
- Funding
- Usage Rights
- Begin Date
- Geographic Description
- Bounding Box coordinates

However, when I pressed **Submit** the first time after filling out those fields, I received the following message: 
![issue0](https://user-images.githubusercontent.com/25068860/38273393-abe62e60-3740-11e8-805c-ef0ef9bd21cb.PNG)

It looked like there was an issue with submitting no data objects. However, when I added a file and attempted to submit, I received the following message: 
![issue1](https://user-images.githubusercontent.com/25068860/38273478-e406caa2-3740-11e8-943a-ea890540609e.PNG)

This time, it looked like there was an issue with the **People** field. I filled in some info for the people field, but there was no button to submit the package. 
![issue2](https://user-images.githubusercontent.com/25068860/38273515-0263cb58-3741-11e8-9e70-b5f72b721fc3.PNG)

**Comment by isteves** [comment] 2018-04-04 15:59
I think I'm getting the same error (also Windows IE11), which is attributed to a "caught exception"

![caught-exception](https://user-images.githubusercontent.com/25118334/38319369-29c2e8a6-3821-11e8-8b1c-08108b8ca143.PNG)

**Comment by isteves** [comment] 2018-04-04 16:10
In trying some more, I also ran into problems with the People field (filled it out with name/position/organization/orcid). I wonder if this problem might be related to #556

**Comment by laurenwalker** [comment] 2018-07-26 18:11
I'm unable to reproduce this bug. It may have been something that has since been fixed in the past 4 months.

**Closed by laurenwalker** 2018-07-26 18:11 UTC
Labels: bug, cannot reproduce, editor
