### ISSUE TITLE
Data file upload errors result in missing resources map and loss of permissions

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#2135] opened 2023-05-17 21:13 UTC
**Describe the bug**
When uploading a dataset over a strong wifi connection (503 mbps down/40 mbps up) over VPN consitently receive upload errors when uploaded files >= 150mb.   

**To Reproduce**
1. Go to dev.nceas.ucsb.edu
2. Click on Submit
3. Upload a 200mb file using a strong wifi connection
4. See upload errors during upload
5. upload smaller files
6. smaller files should upload successfully
7. Save Dataset
8. Go to landing pages and notice you cannot edit nor does the dataset have a resource map. However, all data files are listed in the EML

**Expected behavior**
I should be able to upload a files that is several GBs in size over my current WIFI connection. It is strong and I have never had any problems uploading large files via curl to metacat.  Also, I perform many uploads to other web applications such as google drives and remote backup services.

_**On NCEAS dev during upload**_
<img width="388" alt="Screenshot 2023-05-17 at 1 56 14 PM" src="https://github.com/NCEAS/metacatui/assets/1558129/5d4d6d1e-aebc-4557-aeea-2c58d06abb37">

**Screenshots**
_**On NCEAS dev ui**_
![Screenshot 2023-05-17 at 12 09 51 PM](https://github.com/ess-dive/ess-dive-catalog/assets/1558129/2da0c83a-65ab-44c9-a125-d2f3f7860a7c)

_**On NCEAS  dev after save**_
I was able to upload two 100GB files but the 200GB file failed. Notice that I do not have permissions to edit NOR is there a resource map.  (See https://dev.nceas.ucsb.edu/view/urn%3Auuid%3A8fee3326-fa8f-4637-93a2-2f75909a1600).  Notice that all three files are listed in the EML
![Screenshot 2023-05-17 at 12.27.34 PM.png](https://images.zenhubusercontent.com/5ca65deb411ed363ea8d644b/46b21990-ae7f-4659-ad10-a0e2f29273ef)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Version 113.0.5672.92 (Official Build) (x86_64)

**Additional context**
I tried uploading using a wired connection where I plugged my laptop directly into my router with an ethernet cable. I was able to successfully upload files up to size 1GB. See https://dev.nceas.ucsb.edu/view/urn%3Auuid%3A052ac749-d225-40f4-a72a-6f2d5c3968ff.

I also tried over WIFI without VPN. I was able to successfully upload 200mb files but I still saw the retry error message during the upload. Howver, a 400mb file upload failed.

I think there are two main issues

1. When there are upload errors the metadata editor does not handle the failures gracefully
2. MetadataEditor does not handle WIFI connections as well as it should.

**Comment by vchendrix** [comment] 2023-05-17 21:24
Also had the same issue in Firefox 113.0.1 (64-bit)

**Comment by vchendrix** [comment] 2023-05-17 21:25
@mburrus If we can get the browser version of the ESS-DIVE user that is currently having this problem it would be helpful

**Comment by vchendrix** [comment] 2023-05-17 21:38
Use-case dataset using Firefox no VPN over wifi
https://dev.nceas.ucsb.edu/view/urn%3Auuid%3Aa1d19cfe-4590-43aa-a891-7de455fd6bbf

**Comment by vchendrix** [comment] 2023-05-17 21:59
Chrome 
<img width="1743" alt="Screenshot 2023-05-17 at 2 58 47 PM" src="https://github.com/NCEAS/metacatui/assets/1558129/c53c71ae-7ab5-47af-8dfb-494918790a8a">

**Comment by robyngit** [comment] 2023-05-25 21:58
duplicate of https://github.com/NCEAS/metacatui/issues/2134

**Closed by robyngit** 2023-05-25 21:58 UTC
Labels: bug, ESS-DIVE
