### ISSUE TITLE
only one taxonomicClassification kept

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/metacatui#1523] opened 2020-09-04 16:53 UTC
**Describe the bug**
Only the first taxonomicClassification is kept when you try to add more than one Rank Value pair to one species

**To Reproduce**
1. Go to a dataset and click edit
2. Fill out the taxonomic information in taxa for species 1
- Rank Value
- Phylum Rhodophyta
- Genus Corallina

4. Click submit
4. Only the first rank value pair is saved

**Expected behavior**

**Screenshots**
<img width="1624" alt="Screen Shot 2020-09-04 at 9 04 30 AM" src="https://user-images.githubusercontent.com/13112379/92264695-7d6b2b00-ee93-11ea-92ef-55e170c1906c.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser chrome
 - Version 85.0.4183.83

**Additional context**
Told the PI that the species will be added back in for now.

**Comment by mbjones** [comment] 2020-09-04 18:24
thanks @laijasmine for the report.  While EML does support multiple ranks to be listed for a given taxon, over the years we have discussed that it is probably better to only provide the most specific taxon to which a classification was determined. This is because the organization of the higher-level taxonomies are not fixed and change over time, so the higher-level taxon metadata slowly gets out of date. In an ideal world, here's what I think our system should do:

1) Resesearcher provides the most specific taxon rank to which they classified their specimen(s) -- typically the Species level, e.g., `Ursos arctos`. While the underlying taxonomy shifts at this level too, the researcher's determination never changes.
2) Ideally they also provide a taxon concept identifier for that species concept, or, in the absence of that, a citation to the taxonomic classification that they used
3) Our indexing system takes that species/conceptId, and looks it up in a taxon name system like GNI or ITIS, and we index not just the species level information, but also all of the higher level taxa that are associated with that species. That allows searches for Genus, Family, etc to be accurate.  Periodically we go through and reindex all of our records to pick up changes in taxonomy.

We do not do this now, but it has been on my wish list for a long time. And it would obviate the need to fill in taxon concepts for higher level taxa for people, which reduces their work for metadata entry while also increasing the search accuracy of the system.

So, let's discuss what to do about this bug and how we should go about fixing it over the short term and the longer term.

**Comment by amoeba** [comment] 2020-09-04 20:54
Thanks for the report @laijasmine. Can confirm over on dev.nceas. I think this might actually have already been fixed in https://github.com/NCEAS/metacatui/commit/793bbc55c818df28825c920b060b3536065840ce (July 20th) but not deployed. I'll need to test later once DataONE services come back up so I'll make a note to look later on.

**Comment by laurenwalker** [comment] 2020-10-21 17:41
Just tested this on the latest dev branch and was abble to reproduce this bug. I'll get a fix into 2.13.3

**Closed** 2020-10-21 19:49 UTC
Labels: bug, editor
