### ISSUE TITLE
New Editor: Unable to specify custom format Date-Time format for attribute 

### ISSUE THREAD

**Issue by veeveetran** [NCEAS/metacatui#614] opened 2018-05-08 20:29 UTC
I was unable to update a package via the new editor because I was unable to specify a custom format for a dateTime attribute (year). 

![screen shot 2018-05-08 at 12 57 43 pm](https://user-images.githubusercontent.com/25068860/39781240-7e0ecdfa-52c3-11e8-8a0f-359fffc77954.png)
![screen shot 2018-05-08 at 12 55 44 pm](https://user-images.githubusercontent.com/25068860/39781246-7fddf11a-52c3-11e8-85ca-374983690291.png)

However, the editor has no problem with the other files, which also contained custom Date-Time formats. This screenshot is for `ground_heatflux.csv`: 

![screen shot 2018-05-08 at 1 28 05 pm](https://user-images.githubusercontent.com/25068860/39781312-afded2d0-52c3-11e8-94a7-b4afeec30d80.png)
 
UPDATE: 
The date format was accepted, but I'm still not able to submit my changes: 
![screen shot 2018-05-08 at 1 31 40 pm](https://user-images.githubusercontent.com/25068860/39781736-eec7a692-52c4-11e8-8021-cdf5d4ad7aa8.png)
I was able to make updates yesterday. The things I changed are the taxa section, the entity names and descriptions, and adding superscript 2's and 3's to some of the definitions in the data tables.

**Comment by maier-m** [comment] 2018-05-08 20:46
potentially the same as [#609](https://github.com/NCEAS/metacatui/issues/609)

**Comment by laurenwalker** [comment] 2018-05-16 20:35
I was able to reproduce this error using the 2.0.0 RC 6 code, but when I updated to the 2.0.0 RC 7 code, the error did not occur. I think this was fixed in #609, as Mitchell suggested, because there was not support for changing ratio numeric attributes.

**Closed by laurenwalker** 2018-05-16 20:35 UTC
Labels: bug, editor, in progress
