### ISSUE TITLE
Add ability to add keyword thesauri to a deployment 

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1283] opened 2020-02-27 21:47 UTC

**Comment by csjx** [comment] 2020-03-26 15:33
This is a duplicate of #306 it seems.

**Comment by laurenwalker** [comment] 2020-03-26 16:18
I think it's different in that this ticket is for creating a keyword thesaurus in the MetacatUI configuration, and #306 is for a user to specify an additional thesaurus through the editor UI.

**Closed** 2020-03-31 03:31 UTC
Labels: editor, enhancement
