### ISSUE TITLE
New editor: 'add attribute' label gets pushed out the screen (Windows Firefox)

### ISSUE THREAD

**Issue by rachelsun97** [NCEAS/metacatui#563] opened 2018-04-06 19:44 UTC
![capture](https://user-images.githubusercontent.com/35986952/38440918-d20d5ccc-3997-11e8-948f-c9d8e4fbd592.PNG)

Whenever I start editing the description/measurement scales, the 'add attribute' button and all the attributes I added before gets pushed off of the screen. You have to exit out of the editing box in order and re-enter into it in order to see the attributes and 'add attribute' button again.

**Comment by laurenwalker** [comment] 2018-04-09 22:35
Duplicate of #548

**Closed by laurenwalker** 2018-04-09 22:35 UTC
