### ISSUE TITLE
Prov Editor remove icons get stuck

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#367] opened 2017-11-14 15:28 UTC
When the mouse travels over prov icons, the `mouseover` event enables the remove `X` icon. But it seems to intermittently catch the `mouseout` event, so some of the `X` icons get stuck.  It also seems to be related to the right side of the prov icon. Needs testing. See:

![remove-icons-stuck](https://user-images.githubusercontent.com/1437565/32787933-1ccbecb8-c915-11e7-908c-54a1a7094d74.png)

**Comment by gothub** [comment] 2017-11-14 17:56
This is a duplicate of https://github.com/NCEAS/metacatui/issues/352

**Comment by gothub** [comment] 2017-11-15 17:26
The icons would stick when the cursor exited the prov icon (for data or programs) by traveling
 over the red 'remove' icon.
In this case, the DOM event target became the 'remove' icon itself and not the div containing
the prov 'data' or 'program' icon. The callback handler for the 'mouseleave' event was not handling this case.

The 'stuck' icon problem has been resolved for 'data' icons, in commit 59363329730e909e10ceba52c4412b7237ce65af

The 'program' icons are svg based, so they will need different handling, and have not been
fixed yet.

**Comment by gothub** [comment] 2017-11-15 19:57
Fixed for 'program' icons in commit 036319b980a9d370d32b69a07f8a00471488c5d3

**Closed by gothub** 2017-11-15 19:57 UTC
Labels: bug, provenance
