### ISSUE TITLE
Update DataONE profile view to include quality metrics

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#309] opened 2017-10-17 19:07 UTC
Here is a mockup of metadata quality metrics incorporated into the DataONE view (currently deployed version at https://search-stage.test.dataone.org/#profile/). The quality metrics are shown as the last chart on the following page:

![dataone-profile](https://user-images.githubusercontent.com/6412946/31684160-b7ccb352-b333-11e7-923e-2d8d6bac6157.png)

**Comment by gothub** [comment] 2017-10-17 21:36
Currently Solr does not support a single query that could provide the information needed to generate the "Metadata Quality" panel shown above. The issues are:

- Solr does not calculate cumulative values for date ranges. 
It has been suggested that in order to understand if the metadata quality of a repo, group or DataONE is increasing or decreasing, the stats and numbers shown for each time period should be cumulative to and including that time period, e.g. for 2017 the stats would include all quality scores from 2012 to 2017. A single query cannot do this, instead, a Solr query would have to be issued for each time period show in the chart. 

- Solr 5.1 stats component or higher is required to calculate the quartiles (25% quantiles, solr term = 'percentiles'). 
Metacat currently is using Solr 3.6.2 and the DataONE CNs have Solr 5.2. The current plan is to upgrade Metacat Solr in version 2.9 (https://projects.ecoinformatics.org/ecoinfo/issues/6437)

- Solr cannot create stats for date range facets. Again, separate queries would have to be issued for each time range to calculate the quartiles for that time range. The capability to calculate stats for date ranges may be available in a future version of Solr: https://issues.apache.org/jira/browse/SOLR-6352

**Comment by mbjones** [comment] 2017-10-17 21:58
@gothub -- I've always questioned whether SOLR is the right way for us to implement profile components that need aggregation.  I think we should consider whether maintaining a data cube on the server that is updated via OLAP style processors e.g., daily and is accessible through a stats service API would make more sense and be much higher performing.   This applies to other components as well, such as monthly download and upload stats by various groups.  Let's discuss.

**Comment by gothub** [comment] 2017-10-18 16:27
@mbjones yes we did discuss OLAP during the design phase of the query engine. As Solr indexing of quality metrics wouldn't be available at all until Metacat 2.9, designing/implementing an OLAP solution now makes sense. Apache Hadoop + Kylin is one option. @csjx - any advice on Hadoop + OLAP package?

Having an OLAP server (scalable as virtual cluster) takes the burden off the member nodes having to handle returning quality scores from the quality engine, and then having to Solr index these scores. The MN just has to send the metadata+sysmeta to the quality engine, then the quality engine sends the quality scores to the OLAP server. 

For quality metrics in particular, Kylin can calculate the stats needed for the box plots: http://kylin.apache.org/blog/2017/04/01/percentile-measure.

**Comment by gothub** [comment] 2019-01-30 20:21
For this display, add the ability to plot F-A-I-R subcategory scores over time
First pass would include multi-line line chart over time, one line per category

**Comment by laurenwalker** [comment] 2019-11-18 20:15
Just checking in on this issue since it was originally slated for the 2.8.0 milestone -- I believe we've changed our plans to only show the quality charts on the new portal views. Users and MNs won't have this new chart on their profile views.
Let me know if this isn't the case.

**Comment by gothub** [comment] 2019-11-18 20:25
@laurenwalker yes, I believe that is the case - aggregated quality reports for portals only.

**Comment by laurenwalker** [comment] 2019-11-19 18:43
Ok, I'm going to close this ticket then since it's a duplicate of #1116

**Closed by laurenwalker** 2019-11-19 18:43 UTC
Labels: metadig, metadig-display
