### ISSUE TITLE
Editor not adding line breaks nor indenting into EMLs 

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#832] opened 2018-11-09 21:20 UTC
The new editor does not add line breaks nor indents to EMLs. This feature would be greatly appreciated as it is impeding support team efficiency. Thanks

**Comment by amoeba** [comment] 2018-11-09 22:13
Thanks for the report. 

Just to clarify a tad: Do you mean the serialized XML isn't pretty-printed or are you talking about the formatting of character data inside certain XML elements in the serialized documents? Also, could you describe the way it's impeding efficiency? Maybe we could add something to arcticdatautils to speed something up?

**Comment by jagoldstein** [comment] 2018-11-09 22:39
I'm saying the the serialized EML is not "pretty-printed". We discussed this today on the Arctica call with @laurenwalker and @csjx .

We are training 2 new interns (@kylemonper and @noellepruett) and our training starts them out using the editor UI to make their first submissions. Then they update that EML via R. When new people are introduced to EML in this way, well-formatted examples would go a long way in helping to advance understanding. It's more of an on-boarding (spinning up new interns before they can be unleashed in the RT queue) barrier than it is a barrier to our processing `PROD` content.

**Comment by mbjones** [comment] 2018-11-10 00:05
But we also agreed that pretty-printed XML output should generally be the norm for serializers, as it has virtually no cost, and makes it far easier to read for anyone debugging or opening in a plain text editor.

**Comment by csjx** [comment] 2018-11-10 01:20
I've modified `DataONEObject` to experimentally pretty-print XML in a a feature branch. @jagoldstein - I've installed this on test.arcticdata.io so we can test it out.  It works for me in Chrome/macOS (see https://test.arcticdata.io/view/urn:uuid:671cc036-cbc0-4de0-8964-c33cd2039002), but we need to test it in IE11 and Edge in particular.  I think I have the correct code for those browsers, but haven't tested, so would appreciate it if you could have someone do some cross browser testing.

**Comment by csjx** [comment] 2018-11-10 03:10
Well, seems to be fine on Windows 10, Edge, but there are issues on IE 11 even validating the EML, which seems like a regression unrelated to this change. `creator/individualName/surName` entries don't seem to be updating in the model when added to the metadata. 😕

**Comment by csjx** [comment] 2018-11-11 18:59
> Any time you parse an XML document, the CDATA sections are going to immediately be turned into one or more Text nodes in the DOM

And unfortunately in the `JQuery.parseHTML` case, they are turned into Comment Nodes 🙁

**Comment by mbjones** [comment] 2018-11-12 19:52
Yikes.

**Comment by laurenwalker** [comment] 2019-02-14 22:17
[ ] Test in IE 11

**Comment by csjx** [comment] 2019-02-15 14:48
@laurenwalker - I'm going to close this issue since the functionality is there (as we discussed yesterday).  If you find any issues with IE 11 when you merge to the dev branch, feel free to open this back up.  Just for some closure on my  concerns about losing CDATA sections above - after talking with Matt, it seems we may nave to address the loss of `CDATA` sections until later if the issue comes up (like with serializing project pages).

**Closed by csjx** 2019-02-15 14:48 UTC
Labels: blocker, editor, enhancement

**Comment by csjx** [comment] 2019-02-15 15:24
In fact, after looking at this latest version of the [fiddle](https://jsfiddle.net/csjx/ym2jno6z/7/), both `JQuery.parseXML()` and `DOMParser.parseFromString()` preserve the `CDATA` sections in the DOM, so we have a path forward when serializing XML with `CDATA`.
