### ISSUE TITLE
"Loading editor" message forever

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1315] opened 2020-03-20 18:52 UTC
One of our users experienced this bug while trying to load the editor. Here's a screenshot:

![Screen Shot 2020-03-20 at 1 45 38 PM](https://user-images.githubusercontent.com/6643222/77196371-3c33ba00-6ab1-11ea-8e87-2814662ca022.png)

This is in FF on Windows 10

**Comment by robyngit** [comment] 2020-12-03 21:53
I've been experiencing this issue occasionally as well, though I don't get the XML parsing errors shown in the screenshot. I found a way to consistently reproduce it:

1. Find or create some EML where 1) You have write permission, and 2) The EML does not have an associated resource map
2. Navigate to the EML in the editor (e.g. `https://dev.nceas.ucsb.edu/submit/[EML-PID]`)
3. Navigate to view the EML by clicking on the title at the top of the editor
4. Navigate back to the EML in the editor by clicking the Edit button
5. See loading editor message
6. (Refresh the page, and editor loads).

**Comment by robyngit** [comment] 2020-12-05 02:43
Assuming that the bug originally described was caused by the behaviour above, then this issue is fixed with commit https://github.com/NCEAS/metacatui/commit/ab00e4a3e26b5adb7b3bbdf812efcb4a40d92440

**Closed by robyngit** 2020-12-05 02:43 UTC
Labels: bug, editor
