### ISSUE TITLE
PackageModel.js displays incorrect download count 

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#230] opened 2017-08-17 15:47 UTC
Report from Yi Sun <y.sun5@uq.edu.au>:

> I have 3 metacat2.8.1 instances running on different VMs.
> 
> On 2 of these 3 instances, When I create a new dataset with 2 files
> uploaded, after successfully submission, on the metadata view page, the
> number of Downloads/Views shows a random number immediately(in my case,
> it shows 26 views and 77 downloads).
> 
> I then click the 'online distribution info' link, and refresh the
> browser, the number changed back to 1, which is the correct number.
> 
> I traced the code to PackageModel.js. It seemed that when the record is
> first created, 'read_count_i' is not available in solr index, so the
> number of views/downloads is read from another solr query,
> facet_count.facet_field.pid. In this solr query response,
> facet_count.facet_field.pid shows 26 and 77 respectively. I'm not sure
> where these numbers come from.
> 
> Appreciate if anyone could help me find the right place where this
> "Downloads/Views" is calculated. Thanks very much
> 
> To reproduce the issue,
> 
> login->  create new dataset, include a file -> submit -> check number of
> downloads/views.
> 
> Regards,
> Yi

**Comment by laurenwalker** [comment] 2017-08-17 16:57
This is a duplicate of #229

**Closed by laurenwalker** 2017-08-17 16:57 UTC
Labels: bug
