### ISSUE TITLE
Auto Rendering Feature

### ISSUE THREAD

**Issue by SeanSculleySr** [NCEAS/metacatui#1969] opened 2022-03-15 21:27 UTC
Suggest an enhancement to render .jpg and .txt files automatically in the UI, not having to download. This is a useful feature in the Morpho application.

**Comment by laurenwalker** [comment] 2022-03-15 21:52
Thanks @SeanSculleySr! We do render .jpgs in the Data Files Details section. I'll check to make sure there's not a bug with that feature. Displaying text based files in the UI would also be useful.

**Comment by laurenwalker** [comment] 2022-03-22 16:27
It does look like a bug that images aren't displaying so I created an issue for that (#1982)

We already are tracking the feature of data table previews via #1758. I am going to add a comment to #1758 to state that .txt files would also be a good candidate for previews as well. 

I will close this issue as it is a duplicate of the above mentioned issues.

**Closed by laurenwalker** 2022-03-22 16:27 UTC
Labels: enhancement

**Comment by SeanSculleySr** [comment] 2022-03-22 18:07
Dear Lauren, Thank you kindly! My staff will be pleased.


***@***.***
Regards,

SEÁN P. SCULLEY SNR., PE
Chief, Applied Sciences Bureau
Water Resources Division
South Florida Water Management District
3301 Gun Club Road West Palm Beach, Florida 33406
Office 561.682.6109 / Mobile 561.797.2912
Fax 561.682.5392 / Email ***@***.******@***.***>
