### ISSUE TITLE
Support data layer groups in the layer picker

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1772] opened 2021-05-18 23:25 UTC
For example, we may want layers grouped by category, such as ice, vegetation, fire, etc.

**Comment by robyngit** [comment] 2021-05-19 21:20
(We should allow nested groups as well)

**Comment by robyngit** [comment] 2022-10-03 18:57
This seems to be a duplicate of https://github.com/NCEAS/metacatui/issues/1773

**Closed by robyngit** 2022-10-03 18:57 UTC
Labels: enhancement, pdg, cesium
