### ISSUE TITLE
The Last Pass browser extension breaks the portal layout

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#2046] opened 2022-08-16 15:37 UTC
**Describe the bug**
MetacatUI navbar and footer are out of order

**To Reproduce**
1. Go to `https://arcticdata.io/catalog/portals/DBO/Metrics`

**Screenshots**
<img width="1680" alt="Screen Shot 2022-08-11 at 12 11 32 PM" src="https://user-images.githubusercontent.com/19696935/184918741-28c2c314-d2e7-44a1-8a35-5b1e089a64ef.png">
- [metacat UI loading  DBO metrics - filetype:gif](https://imgur.com/a/wP0riWy)

**Desktop (please complete the following information):**
 - OS: macOS Monterey (v12.4)
 - Browser: Chrome & Firefox
 - Version: Chrome (Version 104.0.5112.79 (Official Build) (x86_64)); Firefox (103.0.2 (64-bit))

**Additional context**
- Only happens on `arcticdata.io`, navbars and footers load correctly on `DataONE.org`
- Verified that it is not a caching issue, tried reloading with cache disabled, and it still gives out of order view.
- This issue persists irrespective of whether the user is signed in.

**Comment by robyngit** [comment] 2022-08-16 19:50
@rushirajnenuji figured out that this issue was caused by a browser extension (lastpass). Turning off this extension fixed the issue for both @rushirajnenuji and @jeanetteclark.

**Comment by robyngit** [comment] 2022-10-06 21:28
Another user reported a broken portal layout today and the culprit was once again the last pass browser extension.

The top bar of the "panels" portal layout extended to fill most of the page:

<img width="1000" alt="Screen Shot 2022-10-06 at 10 42 47 AM" src="https://user-images.githubusercontent.com/26600641/194421456-f6b27f39-29de-4555-be41-61a7f8762c34.png">
<img width="1000" alt="Screen Shot 2022-10-06 at 10 42 40 AM" src="https://user-images.githubusercontent.com/26600641/194421461-04ff2286-cc87-4fe0-a318-69c1af515d2a.png">

This happened in both firefox and chrome, and was resolved in both when the last pass extension was disabled.

The issue seems to result from last pass inserting HTML into the DOM, thereby breaking our layout. Though I feel this is absolutely a last pass bug, the extension is common and breaks our layout completely, and so I think we should try to adapt the portal layout so this stops happening. I doubt last pass will fix this, as [it's been an issue since at least 2015](https://stackoverflow.com/questions/31182317/lastpass-bar-with-an-iframe-breaks-my-css). ([Another case from 2018](https://stackoverflow.com/questions/48197592/last-pass-chrome-extension-creating-a-div-that-blocks-clicks)).

**Comment by robyngit** [comment] 2022-11-03 21:35
Last Pass seems to have recently fixed something so this issue isn't happening any longer in our portals for the chrome extension version 4.102.1. If users are getting this weird layout problem in chrome, the solution is to update the Last Pass extension. (Steps: Go to chrome://extensions, toggle "Developer Mode" in the upper right hand corner, then press the "Update" button that appears near the top).

I am still able to reproduce the issue in Fire Fox with the latest FF Last Pass extension.

**Comment by robyngit** [comment] 2022-11-07 17:14
The issue on FireFox is caused by the extension inserting a blank `<div>` at the top of the `<body>` element:
```
<div style="position: static !important;"></div>
```
Even though the div is empty, our portal layout uses a `grid` display on the body, and so this empty div is treated as the first element in the grid, completely breaking the layout.

I see two options to fix this on our end:
1) Re-design the portal layout to avoid using a grid display on the body
2) Add some javascript that searches for and removes this div. Challenges to this strategy include: selecting only this particular div, which doesn't have an ID; and waiting for the div to be inserted before searching for it. Removing this div could interfere with the behaviour of the extension as well.

I'm reluctant to implement either of this workarounds in MetacatUI for something that is clearly a bug in the extension, though I'm open to other view points. I've contacted the LastPass support via email and their web forum to report the bug and ask if & when a fix is planned. Given that this behaviour was recently fixed in the Chrome extension, I suspect that a fix for the FireFox extension will come soon. In the meantime, I suggest that users disable the LastPass extension while viewing portals with FireFox, or view in Chrome with the most recent version of the extension.

I am going to close this issue with the `will-not-fix` tag for now, but it can be re-opened if we decide that it is causing enough problems to warrant a layout re-design.

**Closed by robyngit** 2022-11-07 17:14 UTC
Labels: bug, portals
