### ISSUE TITLE
removing and adding files leaves stranded entity info

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#1095] opened 2019-09-14 19:04 UTC
When I updated a data package by removing files and adding their replacements in MetacatUI, the resulting [saved data package](https://knb.ecoinformatics.org/view/urn:uuid:2b7ce46c-18ed-4afd-89ad-578102214230) still shows the original files as other entities (but without the prov editing icons) as well as the new files (with prov editing icons).  See the attached screenshots showing the state after submitting and viewing the package:

1) the table lists the proper files
<img width="1259" alt="package-table" src="https://user-images.githubusercontent.com/766407/64912652-d0762c00-d6de-11e9-8f06-940d66974da9.png">

2) the otherEntity section shows old files that shouldn't be in the package at all (and without previews or PROV icons):
<img width="1258" alt="package-entities" src="https://user-images.githubusercontent.com/766407/64912659-d79d3a00-d6de-11e9-97b9-0c4991066c59.png">

NB: It would be better to be able to replace files in one step as described in #653 but this is a workaround that should still work (albeit requiring all metadata to be re-entered for each replaced entity).

**Comment by mbjones** [comment] 2019-09-14 19:05
One other note -- I removed the Rmd file as well and added a new Rmd file, but dor some reason it is not showing the old version like happens for the csv and png files. Not sure why.

**Comment by laurenwalker** [comment] 2019-09-16 15:34
Hmm, I know we've seen this bug before but I thought I fixed it already. I'll look into it

**Comment by laurenwalker** [comment] 2020-01-16 23:31
I believe this is a duplicate of #1217, but I'll leave it open so we can verify that when we fix it.

**Comment by laurenwalker** [comment] 2020-01-22 01:00
These three related bugs: #1172, #1217, #1095 are all now fixed with the same commit referenced above.  Please let me know if you continue to see this behavior, since it's possible more than one set of steps cause this bug (but I was only able to find one, after LOTS of debugging).

**Closed by laurenwalker** 2020-01-22 01:00 UTC
Labels: bug, provenance
