### ISSUE TITLE
Editing packages with data that you don't have changePermission on

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1392] opened 2020-05-19 21:00 UTC
I tried editing a data package with 3 data objects:

Data obj 1: I have read, write, and changePermission
Data obj 2. I have read permission only
Data obj 3. I have read permission only

The resource map and metadata doc were updated successfully, but the Data 2 and Data 3 were not included in my new package. The editor attempted to update the sys meta of Data 2 and Data 3 (as a part of the DataPackage.save() process), but these obviously failed from 401 errors. But they should not have been removed from the package.

This will especially become an issue once we have the EML Editor Share options enabled (#1231)

**Comment by robyngit** [comment] 2020-11-25 22:27
Closing because this is a duplicate of #1418

**Closed by robyngit** 2020-11-25 22:27 UTC
Labels: Priority: High, bug, duplicate, editor
