### ISSUE TITLE
New entries are labeled as archived

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#147] opened 2017-06-19 16:40 UTC
When using the editor to create a brand new package, the `CitationView` is displaying:

> Christopher Jones. Veggies es bonus vobis, proinde vos postulo essum. null. . urn:uuid:dbe8a002-30e0-4094-9e45-24e0591a1534. This content has been archived. urn:uuid:dbe8a002-30e0-4094-9e45-24e0591a1534.

Steps to reproduce:

1. Log in
2. Navigate to `/#share` using `Submit Data` button
3. Edit the title
4. Choose `Submit`

Check to see if we are setting the archived flag in the `SystemMetadata` on new content.

**Comment by csjx** [comment] 2017-06-19 20:45
In fact, the messages seem to multiply after edits:
![archived-issue](https://user-images.githubusercontent.com/1437565/27305159-c641fa26-54fd-11e7-8196-6721810f1d97.png)

**Comment by laurenwalker** [comment] 2017-06-27 21:16
I am unable to reproduce this error. Which version of Metacat was this pointing to?

**Comment by csjx** [comment] 2017-06-27 23:11
Hmm. I have Metacat 2.8.1 installed.

**Comment by laurenwalker** [comment] 2017-06-28 20:54
I am unable to reproduce this with the up-to-date master branch code while pointing to a 2.8.1 metacat. I'm going to close this issue. We can reopen if it is indeed an issue with the current code.

**Comment by laurenwalker** [comment] 2017-07-18 20:27
Now that I've merged a bunch of code from Chris, I'm starting to experience this issue. Reopening.

**Closed** 2017-07-24 21:09 UTC
Labels: bug
