### ISSUE TITLE
Support changing the color of features in a data layer

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1768] opened 2021-05-18 23:19 UTC
Users should be able to change the color or color scales of the features in a data layer in Cesium (after MVP)

**Comment by robyngit** [comment] 2021-05-19 21:55
This should also include updating the legend dynamically based on colour choices.

**Comment by robyngit** [comment] 2021-06-15 20:46
Reminder that when it comes to colour scales, we should provide users a choice of scientifically derived and perceptually uniform gradients, see the article [Crameri, F., Shephard, G.E. & Heron, P.J. The misuse of colour in science communication. Nat Commun 11, 5444 (2020)](https://www.nature.com/articles/s41467-020-19160-7).

**Comment by robyngit** [comment] 2021-11-29 17:36
If this issue is referring to the ability to _configure_ colors for a layer in a cesium map, it is now ready in the `develop` branch, with the exception of [continuous and classified color palettes](https://github.com/NCEAS/metacatui/issues/1888). If this issue is instead referring to creating a UI for people to change layer colors while viewing a map, then it is a duplicate of https://github.com/NCEAS/metacatui/issues/1798

**Closed by robyngit** 2021-11-29 17:36 UTC
Labels: enhancement, pdg, cesium
