### ISSUE TITLE
prov relationships lost upon publish with DOI

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#972] opened 2019-06-15 21:35 UTC
Summary:  When publishing a package on the KNB production MetacatUI editor with a DOI, previously established PROV relationships no longer show up.  This could be related to issue #946 in which the resource map is mangled when publishing with a DOI.

Example data set missing PROV display: https://doi.org/10.5063/F1KP80GX

I created a [first package](https://knb.ecoinformatics.org/view/urn:uuid:7f023f58-d48b-4d2e-9f78-5ad3527e4b3b) with one data file, one Rmd script, and image files, saved it, and then added provenance relationships to the package linking the components.   These can be seen in the [package display for the first package](https://knb.ecoinformatics.org/view/urn:uuid:7f023f58-d48b-4d2e-9f78-5ad3527e4b3b). 

I then edited this in MetacatUI to add an additional creator which created a new data set in which the provenance relationships are still correct and displayed in the [second version of the data set](https://knb.ecoinformatics.org/view/urn:uuid:66e76292-46f9-4e51-8d54-d30ab87f4ec7).

Finally, I pressed `Publish with DOI` button, which created a [third version of the data set](https://knb.ecoinformatics.org/view/doi:10.5063/F1KP80GX), and the provenance information is not displayed.  It should still be displayed because none of the constituent data files changed in the package.

PID relationships:
- `urn:uuid:7f023f58-d48b-4d2e-9f78-5ad3527e4b3b` obsoletedBy `urn:uuid:66e76292-46f9-4e51-8d54-d30ab87f4ec7`
- `urn:uuid:66e76292-46f9-4e51-8d54-d30ab87f4ec7` obsoletedBy `doi:10.5063/F1KP80GX`

@laurenwalker Can you fix this along with #946 please?

@jeanetteclark Can you determine if we need to systematically fix mangled packages that were created with the 'Publish with DOI' button?  Let's discuss.

**Comment by laurenwalker** [comment] 2019-06-17 14:40
I'll look into this and see what is causing the issue. It *may* be a Metacat issue during the publishing process, or it may be an issue with MetacatUI parsing the new resource map.

**Comment by jagoldstein** [comment] 2019-06-17 17:13
This issue has persisted for at least the last year and a half.
Related to #478 and https://github.nceas.ucsb.edu/KNB/arctic-data/issues/290

The support team has to be mindful of adding prov relationships back to packages as a LAST STEP, otherwise those relationships will not be displayed; updating the package will result in prov no longer rendering.

**Comment by jeanetteclark** [comment] 2019-06-17 17:56
Yup - its on my list to go back and add prov relationships to ALL of the SASAP packages since they have all been removed as a result of this bug

**Comment by laurenwalker** [comment] 2019-06-17 18:00
The issue #478 you linked to, @jagoldstein, was fixed back in March in the referenced commit. The issue was opened back up by Peter because the way that it was fixed *may* cause issues in test environments since it essentially changed all the CN test URLs with the production cn.dataone.org URLs. (See the conversation on that ticket). I've actually been fixing that along with the fix to #946.

I'm not sure if #290 is a separate bug or the same issue. And since that bug was happening back when we had 2.0 deployed in beta and 1.X deployed in production, I think it isn't relevant anymore. Since the way the prov charts were displayed in 1.X were different than in 2.X, we were seeing that "issue" a lot. So that's been fixed, since.

It's not my understanding that prov relationships are *always* being removed with *any* edits in the editor. If that has been an issue for months, I wish you would have bugged me about it more! Have you experienced these issues since we moved from beta?

I'll do some more testing and make sure we have an up-to-date assessment on what the bugs are.

**Comment by jeanetteclark** [comment] 2019-06-17 18:03
I believe the relationships are removed when making updates via `arcticdatautils` as well, which might require a separate ticket.

**Comment by jagoldstein** [comment] 2019-06-17 18:06
Yes, any update wipes prov relationships (on the front end at least). It does not seem to matter HOW the updates are made. This has often been brought up in Slack, GH, and on weekly calls.

**Comment by laurenwalker** [comment] 2019-06-17 18:59
I didn't know this was still an issue after we moved from beta over a year ago. I'll look into it.

**Comment by laurenwalker** [comment] 2019-06-18 21:03
Moving this to 2.6.4 so I can get the major bug affecting DOI resource maps deployed

**Comment by jeanetteclark** [comment] 2019-06-18 21:06
@mbjones thanks to some help from @csjx and @amoeba I identified 17 mangled resource maps on production. I'll work on making sure that they are updated with non-mangled versions.

**Comment by laurenwalker** [comment] 2019-06-18 21:35
Could you send me the list of those resource map ids, @jeanetteclark ?

**Comment by jeanetteclark** [comment] 2019-06-18 21:36
```
"urn:uuid:087a1684-00da-476d-ab93-b90ff0ae9725"
"urn:uuid:c7738e9c-ca2b-4559-8d5e-9306a1649e61"
"urn:uuid:1f4f4ae4-9e6f-4d49-a59f-218b95b24ec0"
"urn:uuid:03061ce4-8c3c-4ef3-b544-da65fbad234e"
"urn:uuid:bfe6787e-2b3c-45b3-b4bf-f78894ac1318"
"urn:uuid:23ef3329-fe3f-4535-98ed-2bfb96e3c398"
"urn:uuid:02d96394-8d43-4324-8d95-70fd1e1ae8e2"
"urn:uuid:b05f9ab2-7acb-49a0-a104-f3f3bda21d92"
"urn:uuid:0faa6d96-22aa-4df0-a643-2ffaa17736ac"
"urn:uuid:9b615c4f-7ced-4472-91b8-70e8396ea05d"
"urn:uuid:ff6eb319-cd3e-420b-9bd3-f608c8914418"
"urn:uuid:5be28240-01b9-46db-9462-8b317cf1a525"
"urn:uuid:3cb9f915-4af9-4a43-9cfc-3ba09f972453"
"urn:uuid:37932206-7f24-4021-bb9a-0dd2f42047a8"
"urn:uuid:0dcb222b-e9be-462e-8d04-e533ee5d2454"
"urn:uuid:8f382644-e0f4-436b-b206-0b6753023d63"
"urn:uuid:7d7254cb-7b51-4e16-a389-fd1aa7af1a39"
```

**Comment by jeanetteclark** [comment] 2019-06-18 22:13
The last one in this list is particularly strange - the result of me trying to add prov to https://doi.org/10.5063/F1ZW1J77

**Comment by jeanetteclark** [comment] 2019-06-19 17:48
Doing some testing I recreated this by:

creating a package on dev using metacatUI
publishing with a DOI using the button
adding prov using metacatUI

The result is this resource map: `resource_map_urn:uuid:88916868-eb15-4423-898a-3c1439637067` which is missing `documents` and `isDocumentedBy` statements

**Comment by laurenwalker** [comment] 2019-06-19 18:02
Thanks Jeanette

**Comment by jeanetteclark** [comment] 2019-06-19 19:57
@laurenwalker I also confirmed with @amoeba that `arcticdatautils` knowingly removes prov when a package is updated. @jagoldstein I'll start a ticket in the `arcticdatautils` repo to discuss the best approach to fix that

**Comment by laurenwalker** [comment] 2019-06-25 21:08
This issue is now fixed. The solution was the same as #946, just in a different part of the code. 

I've done a lot of testing today to make sure this works, but further testing by others would be nice, too. I've deployed the fix to dev.nceas for others to test with.

While testing, I discovered a related Metacat bug where publishing with a DOI fails if done after adding provenance: https://github.com/NCEAS/metacat/issues/1363

**Closed by laurenwalker** 2019-06-25 21:08 UTC
Labels: Priority: Critical, blocker, bug, in progress, provenance
