### ISSUE TITLE
Geotag global datasets as somewhere in the Arctic rather than having seemingly random datasets in Nigeria

### ISSUE THREAD

**Issue by erinlynmclean** [NCEAS/metacatui#1751] opened 2021-05-13 16:46 UTC
**Describe the feature you'd like**
Geotag global datasets as somewhere in the Arctic rather than having seemingly random datasets in Nigeria

**Additional context**
Requested from the portals focus groups

**Comment by laurenwalker** [comment] 2021-05-18 18:05
Duplicate of #700

**Closed by laurenwalker** 2021-05-18 18:05 UTC
Labels: enhancement, portals, portals focus group
