### ISSUE TITLE
Add feature to reorder authors in Metacat UI

### ISSUE THREAD

**Issue by charuleka** [NCEAS/metacatui#810] opened 2018-10-19 23:26 UTC
Title: Ability to reorder authors in Metacat UI

Would it be possible to enhance the metacat UI form so users can reorder authors? It is very typical for many of our datasets to have 20+ authors and the current interface makes it extremely challenging to manage authors. 

This issue documents some of the usability problems trying to reorder an author list, and add/delete authors. I am working on the ESS-DIVE UI (MetacatUI 2.0.0)

As an example, we just received a typical request where the user wanted to change the authors for a package. 
FROM
Prinn R; Weiss R; Krummel P; O'Doherty S; Fraser P; Muhle J; Reimann S; Vollmer M; Simmonds P; Maione M; Arduini J; Lunder C; Hermansen O; Young D; Wang H (; Huang J; Rigby M; Harth C; Salameh P; Spain T; Steele L; Arnold T; Kim J; Manning A; Derek N; Mitrevski B; Miller B 
TO
Prinn, R. G., Weiss, R. F., Arduini, J., Arnold, T., DeWitt, H. L., Fraser, P. J., Ganesan, A. L., Gasore, J., Harth, C. M., Hermansen, O., Kim, J., Krummel, P. B., Li, S., Loh, Z. M., Lunder, C. R., Maione, M., Manning, A. J., Miller, B. R., Mitrevski, B., Mühle, J., O'Doherty, S., Park, S., Reimann, S., Rigby, M., Saito, T., Salameh, P. K., Schmidt, R., Simmonds, P. G., Steele, L. P., Vollmer, M. K., Wang, R. H., Yao, B., Yokouchi, Y., Young, D., and Zhou, L.

It was a heavy lift to reorganize the author listing. First I tried to edit in the web form directly - this was too difficult to keep track of, esp since the authors each had their ORCIDs and emails, and mistakes were likely to occur while cutting and pasting the information for a large number of authors. The form UI for authors was unusable for this purpose.

We then thought it would be easier to edit the XML directly.  The original  XML downloaded makes </creator> appear on the same line as the creator tag of  a new person, which is unwieldy, so the XML had to be reformatted. Overall, it  took about half an hour to edit the XML and cut and paste the blocks correctly.

It is almost unimaginable that any scientist would jump through such hoops just to reorganize  an author listing.  A simple reorder functionality (either through a dropdown or drag and drop), such as those present in almost any manuscript submission website would make this much easier and more efficient for users.

**Comment by laurenwalker** [comment] 2018-10-23 16:28
Sounds like a useful feature to me. I'll schedule this in.

**Comment by mbjones** [comment] 2018-10-31 23:32
This was in our original discussions and is a much needed feature.   +1
from me.

**Comment by laurenwalker** [comment] 2019-02-20 20:57
Duplicate of #521.

**Closed by laurenwalker** 2019-02-20 20:57 UTC
Labels: editor, enhancement
