### ISSUE TITLE
Ability to choose from preconfigured citation formats in the CitationView

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#1607] opened 2020-11-19 20:50 UTC
**Describe the feature you'd like**
The only way one can change the format of the citation of data packages in metacat ui is to override the render function of the CitationView.   It would be nice if metacatUI provided a list of common citation formats to choose from (Chicago, Datacite, MLA, custom..) when configuring th UI

**Is your feature request related to a problem? Please describe.**
ESS-DIVE requires a specific citation format and would like it's format to be one of those in the chosen list

**Additional context**
This is related to #567

**Comment by mbjones** [comment] 2020-11-19 22:45
I think this is a duplicate of #973. @val, can you confirm or describe what might differ? Thanks.

**Comment by vchendrix** [comment] 2020-11-19 22:57
@mbjones This is just a ticket that fell out of our tech discussion. It is not a priority of ESS-DIVE but it was something we thought would be good to capture.  @csjx Do you think this captures  our discussion?

**Comment by laurenwalker** [comment] 2021-01-12 19:57
Closing as it sounds like a duplicate of #973. We can reopen if there's clarification on how it's different. Thanks

**Closed by laurenwalker** 2021-01-12 19:57 UTC
Labels: ESS-DIVE, enhancement, metrics-display
