### ISSUE TITLE
license info not "structured" on document page

### ISSUE THREAD

**Issue by yvanlebras** [NCEAS/metacatui#1264] opened 2020-02-03 13:46 UTC
Hi NCEAS,

Testing data structuration of several data catalog pages (Geonetwork vs GBIF vs [our test Metacatui-based catalog](https://openstack-192-168-100-101.genouest.org/metacatui/view/urn:uuid:c60e3dda-ba58-4a2b-9395-4af83ca13b48)) through [Google data structuration test service](https://search.google.com/structured-data/testing-tool?), It detects that the license is not structured (seee warning message below and test results [here](https://search.google.com/structured-data/testing-tool?hl=fr#url=https%3A%2F%2Fopenstack-192-168-100-101.genouest.org%2Fmetacatui%2Fview%2Furn%3Auuid%3Ac60e3dda-ba58-4a2b-9395-4af83ca13b48))

![image](https://user-images.githubusercontent.com/7910679/73657952-9d373800-4693-11ea-8eb1-ebad54284845.png)

First of all, Too cool that major part of the document page is structured in a way that Google datasearch can identify content !! (Geonetwork dosn't seems to have that structuration by default...). So maybe there is something to do on metacat so the JSON-LD files are well formatted for license information ?

**Comment by amoeba** [comment] 2020-02-03 18:28
Hey @yvanlebras, thanks for the report and the link to the result so I could check it out. This issue looks like a duplicate of #1076 and relates to #1147. We don't currently write license info into our JSON-LD due to architecture changes we need to make but it's on the list for sure.

**Comment by yvanlebras** [comment] 2020-02-03 19:30
Thank you very much for your fast and detailled message. Really sorry I don't see the duplication, you're totally right! If this is on the list, PERFECT!

You are so amazing NCEAS team.

Wishing you a happy week.

Yvan

**Comment by laurenwalker** [comment] 2020-02-06 19:01
Closing this issue since it is a duplicate of #1076

**Closed by laurenwalker** 2020-02-06 19:01 UTC
Labels: jsonld
