### ISSUE TITLE
Authors missing in the citation of the dataset landing page

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/metacatui#1674] opened 2021-03-02 18:04 UTC
**Describe the bug**
The dataset here is missing the authors at the top (Robert and Leah). The information is in the creator section of the metadata.

**To Reproduce**
1. I cloned the dataset to test.arcticdata.io
2. At the cloned [dataset](https://test.arcticdata.io/view/urn:uuid:43601b56-5f3b-4755-8825-cca7274a9d23) I clicked the edit button
3. Save the dataset
4. See that the authors are now populated in the [new version](https://test.arcticdata.io/view/urn%3Auuid%3A556d59df-9f52-4b47-8541-61508d3ffbff) at the top

**Expected behavior**
The authors should have been displayed. 
https://arcticdata.io/catalog/view/urn:uuid:5074e51a-f8db-49ac-b517-6535df6ff525 <- first version
https://arcticdata.io/catalog/view/urn:uuid:9d2d7d7e-6a47-40e7-84a4-b65b228852f2 <- version missing the authors
https://arcticdata.io/catalog/view/urn:uuid:4325853b-ea89-4571-b005-a893f0227c3e <- fixed

**Desktop (please complete the following information):**
 - Browser: chrome
 - Version 88.0.4324.182

**Comment by amoeba** [comment] 2021-03-04 00:47
Thanks for the report @laijasmine and all the info that'll help debug.

I'll take a look.

**Comment by amoeba** [comment] 2021-03-04 01:00
Looks like this was caused by the use of EML `references` which, while valid EML, isn't supported by our indexing software and the index is what backs that citation. The document missing its authors starts with...

```xml
  <dataset>
    <title>Arctic Observing Network (AON) observations from the 2010-2011 Beaufort shelf-edge mooring array</title>
    <creator>
      <references>reference_1</references>
    </creator>
    <creator>
      <references>reference_2</references>
    </creator>
```

In addition to the index, I don't think the MetacatUI editor supports references either. We might need to do a better job explaining that to users and datateam members. You appear to have gotten to the fix which is to use `creator` elements that don't use `references`. I'm guessing you just edited the version with missing creators, saw there were none, and MetacatUI removed the `reference`d creators and inserted the new ones you made?

We already have a bug on the appropriate repo to track the indexing side of this at https://github.com/NCEAS/metacat/issues/926 so I'm going to close this.

**Closed by amoeba** 2021-03-04 01:00 UTC
Labels: bug

**Comment by laijasmine** [comment] 2021-03-04 01:03
Ah ok thanks Bryce for looking into this! That all makes sense. I'll make sure to add that to the training manual for now

**Comment by mbjones** [comment] 2021-03-04 19:34
I consider it a serious bug if either MetacatUI or the DataONE indexer do not support EML references. It is a core part of the metadata language that has been in use for decades, and we had no trouble handling it in Morpho. Are there bug reports for this in both products?

**Comment by amoeba** [comment] 2021-03-05 02:11
@mbjones I coulda sworn we had tickets for both Metacat and MetacatUI but I only found one for Metacat. So I made a new one for MetacatUI.

Metacat: https://github.com/NCEAS/metacat/issues/926
MetacatUI: https://github.com/NCEAS/metacatui/issues/1680
