### ISSUE TITLE
Allow users to 'follow' portals for updates

### ISSUE THREAD

**Issue by aebudden** [NCEAS/metacatui#1845] opened 2021-08-05 04:24 UTC
Add the capability for the community to 'follow' portals so that users are aware when there have been updates. Possible related to issue #1744 

This request came in from David Allen (NOAA) via Sandy Starkweather (NOAA) in response to the portals focus group update email.

**Comment by laurenwalker** [comment] 2021-08-05 14:16
Thanks Amber. Were any specific kinds of updates mentioned? (updates to the content of the portal or the datasets in the portal)?

**Comment by aebudden** [comment] 2021-08-05 15:06
No, no more details. I followed up via email talking about different types of updates (portal features(MetaCatUI), datasets in the portal, knowing about new portals)

**Comment by robyngit** [comment] 2023-05-17 21:05
Duplicate of #1744

**Closed by robyngit** 2023-05-17 21:05 UTC
Labels: enhancement, portals, portals focus group, arctic data center, ADC CI-18
