### ISSUE TITLE
Add a "Reset"/"Cancel" button to the EditCollectionView

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1057] opened 2019-08-15 19:43 UTC
See my comments in #991 

Add a button that allows the user to set the filters back to the collection definition filters that were originally set on the collection (i.e. what is already saved in the collection document).

**Comment by robyngit** [comment] 2021-01-26 19:27
This is now a duplicate of https://github.com/NCEAS/metacatui/issues/1581

**Closed by robyngit** 2021-01-26 19:27 UTC
Labels: Portal Editor
