### ISSUE TITLE
Test site isn't showing private datasets in the catalog

### ISSUE THREAD

**Issue by dvirlar2** [NCEAS/metacatui#2158] opened 2023-07-07 18:12 UTC
**Describe the bug:**
After the cesium upgrade, it looks like the [test site](test.arcticdata.io) is _for the most part_ not showing private datasets in the catalog. I say "for the most part" because on [page 5](https://test.arcticdata.io/page/5) and [page 7](https://test.arcticdata.io/page/7) I can see private datasets from Jeanette and Jing, respectively. However, a new private dataset I just made, and a private dataset from one of my interns, isn't showing up in the catalog. 

I can still find the private datasets from myself and my intern by navigating to our profiles, and viewing the datasets associated with our ORCIDs though. So it seems like the datasets aren't hidden from other team members, but rather that the catalog isn't showing private datasets after a certain date. I'm guessing that date is sometime after Jeanette's dataset on page 5 was created.

When refreshing the page, my private dataset shows up a brief moment in the catalog before being removed. 

<br> 

**Expected behavior:**
The search catalog should be displaying private datasets. 

<br> 

**Desktop:**
 - OS: Monterey (Version 12.6.7 (21G651))
 - Browser: Chrome
 - Version: 114.0.5735.198 (Official Build) (x86_64)

**Comment by robyngit** [comment] 2023-07-10 14:36
Thanks for reporting this @dvirlar2! Do you have an example or two of private datasets that are _not_ showing up?

**Comment by dvirlar2** [comment] 2023-07-10 16:39
Yes I do! I created a dataset last week to test target paths, which you can find here: [_"Filepaths test - orcas data -- this worked!"_](https://test.arcticdata.io/view/urn%3Auuid%3Ae86970bc-0891-449e-88b2-6be36ad9d815). 

The other dataset that should be visible but isn't showing up is from my intern Kira: [_"Arctic aggregated and original land cover classes derived from Global Land Cover 2000 dataset"_](https://test.arcticdata.io/view/urn%3Auuid%3Afc88717f-914b-4f92-aa78-c90d1cfd4bec)

But just know while looking for Kira's private dataset, I realized she actually has public datasets as well that aren't showing up in the catalog. The list of her datasets can be found on her [profile](https://test.arcticdata.io/profile/http://orcid.org/0009-0007-4979-0313)

**Comment by robyngit** [comment] 2023-07-10 16:43
🧐 how very strange, I'll look into it! Thank you for the details!

**Comment by dvirlar2** [comment] 2023-07-10 16:43
The catalog _does_ show the datasets when you first navigate to the page, but then it quickly/immediately reloads itself. I managed to get a screenshot (below) of what the catalog looks like before it refreshes itself 🙂 


<img width="1920" alt="Screen Shot 2023-07-10 at 9 39 05 AM" src="https://github.com/NCEAS/metacatui/assets/98365096/e665afbf-8a6a-443c-a6c4-0b2afb5e99ac">

**Comment by dvirlar2** [comment] 2023-07-10 21:29
@robyngit I just tried looking for a dataset on the production site, and for some reason it isn't showing up in the catalog. The dataset is [_"Parameters for estimating methane emissions from Arctic-boreal lakes: non-inventoried small lake areas, aquatic vegetation, and potential double-counting with wetlands"_](https://arcticdata.io/catalog/view/urn%3Auuid%3A35ccd85f-8168-40b4-bc67-44c5946811d4). I made a small update to the dataset to see if that would change the permissions and fix it not showing up, but no dice 🫠 

So far it looks to be the only dataset affected on the production site... I'll let you know if I come across others

**Comment by robyngit** [comment] 2023-07-11 12:57
Thanks for the update and additional example, @dvirlar2. I'm working on this and will try to get a fix released ASAP.

**Comment by robyngit** [comment] 2023-07-13 15:09
@dvirlar2 the reason ["Parameters for estimating methane emissions from Arctic-boreal lakes: non-inventoried small lake areas, aquatic vegetation, and potential double-counting with wetlands"](https://arcticdata.io/catalog/view/urn%3Auuid%3A35ccd85f-8168-40b4-bc67-44c5946811d4). doesn't show in the ADC catalog is that it lacks geographic coverage metadata and the catalog limits the search results to the visible area of the globe by default. If you uncheck LIMIT SEARCH TO MAP AREA, then this particular dataset _is_ in the catalog.

<img width="1439" alt="Screenshot 2023-07-13 at 11 07 35" src="https://github.com/NCEAS/metacatui/assets/26600641/102d2aca-1cc2-4c55-b633-ee88d862b4eb">

Is this unexpected behaviour? Should we _not_ limit search results to the geographic area until the user first starts panning/zooming on the map, perhaps? What do you think?

(Still investigating the test site datasets.)

**Comment by robyngit** [comment] 2023-07-13 18:15
Seems like the two issues here are:
1. Faulty coordinates in the Geographic Coverage of the datasets (north and south bounding box coordinates were reversed)
2. The catalog map limits the search to the map area before the user has interacted with the map, unlike the behaviour in the old catalog search.

I've made separate issues to cover these tasks (#2159 and #2160)

Also, a note that test.adc website was also on an older dev version of MetacatUI. This might have been causing some of the unexpected behaviour with the catalog. It's now running the 2.25.0.

**Closed by robyngit** 2023-07-13 18:15 UTC
Labels: bug, Priority: High
