### ISSUE TITLE
Allow the portals to be able to use custom domains

### ISSUE THREAD

**Issue by erinlynmclean** [NCEAS/metacatui#1738] opened 2021-05-12 23:43 UTC
**Describe the feature you'd like**
Allow the portals to be able to create custom domains so that they can act as full-fledged websites

**Additional context**
Requested from the portals focus group

**Comment by laurenwalker** [comment] 2021-05-18 19:36
Duplicate of #1700

**Closed by laurenwalker** 2021-05-18 19:36 UTC
Labels: DataONE Plus, enhancement, portals, portals focus group
