### ISSUE TITLE
editing `entityName` results in two entities for the same file

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#1246] opened 2020-01-16 16:59 UTC
Editing the `entityName` in metacatUI results in two entity entries for the same file. See this as an example:

https://test.arcticdata.io/view/urn:uuid:ca365745-e4b4-425d-9feb-9ccf07bb8896

Since entity information in the metadata record is often linked to the entities themselves by the filename in the systemMetadata (I think) I'm wondering if we should  disallow editing `entityName` in the editor. I have seen several users write in that they cannot edit information about their entity after it has been submitted, and while I think that is largely due to this [issue](https://github.com/NCEAS/metacatui/issues/1172), this double entity situation also causes problems.

**Comment by laurenwalker** [comment] 2020-01-28 02:21
This bug may have been fixed already on the dev-2.9 since I recently fixed related bugs. @rushirajnenuji, I see that you self-assigned this issue. Just do a quick test to see if this bug still exists before spending too much time on this, because I think it's likely fixed already.

**Comment by laurenwalker** [comment] 2020-01-30 18:35
I tried to reproduce this and I believe this was fixe along with the other related bugs.

**Closed by laurenwalker** 2020-01-30 18:35 UTC
Labels: bug
