### ISSUE TITLE
Missing authors in citation

### ISSUE THREAD

**Issue by charuleka** [NCEAS/metacatui#1044] opened 2019-08-07 16:00 UTC
When two creators are entered with the same first name and last name, but different organizations, the citation doesn't have both the names.

See
https://data-stage.ess-dive.lbl.gov/view/ess-dive-673951be334c80e-20190807T155749903

**Comment by amoeba** [comment] 2021-02-19 02:16
I think this is fundamentally caused by the same issue as https://github.com/NCEAS/metacat/issues/1374 and resolved by the same fixes.

**Comment by mbjones** [comment] 2022-02-18 22:22
This issue arose again today for the Arctic Data Cneter. Bumping to high priority.

**Comment by laurenwalker** [comment] 2022-02-21 17:16
@mbjones This issue is caused by NCEAS/metacat#1374. I'm pinging @taojing2002 so he is aware it is high priority. It looks like he has it slated for the 2.17.0 release anyway.

**Comment by robyngit** [comment] 2022-10-03 20:21
Closing as this is a Metacat issue (https://github.com/NCEAS/metacat/issues/1374)

**Closed by robyngit** 2022-10-03 20:21 UTC
Labels: ESS-DIVE, Priority: High, query builder
