### ISSUE TITLE
Combination of EML annotation and custom xml safe generated identifiers raise error on save

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#2038] opened 2022-07-13 20:34 UTC
**Describe the bug**
When updating a dataset with a repository that implements a custom MetacatUI theme that generates custom identifiers which are already xml safe (e.g. ess-dive-dd8dedc5a811a10-20220713T153145487), the following error is raised

<img width="1428" alt="Screen Shot 2022-07-13 at 1 25 15 PM" src="https://user-images.githubusercontent.com/1558129/178828020-eba2155e-91de-4538-8aa7-7e57c876a372.png">

**To Reproduce**
1. Go to https://data-dev.ess-dive.lbl.gov/submit/ess-dive-0d45cb965fa7c66-20220623T162058401017
2. Edit the title
3. Click "Submit Dataset"

**Expected behavior**
The problem is that  `eml.packageId` and `eml.dataset.id` are the same and that causes this error.  Looking in the code I can see that replace the use of  `this.getXMLSafeID()` with `this.getUniqueEntityId(this)` to make sure that the identifier is unique.

https://github.com/NCEAS/metacatui/blob/47e7b5566fb74a7744d5efc478f0147548509a8b/src/js/models/metadata/eml211/EML211.js#L952

**Desktop (please complete the following information):**
 - OS:  MacOS X Monterey
 - Browser:  Chrome
 - Version: 103.0.5060.114 (Official Build) (x86_64)

**Comment by vchendrix** [comment] 2022-07-13 20:45
Hi @laurenwalker, this is a pretty high priority issue as it is preventing us from editing datasets with annotations.  Thanks!

**Comment by mbjones** [comment] 2022-07-13 23:10
@vchendrix You say that "The problem is that `eml.packageId` and `eml.dataset.id` are the same", but that has always been the case -- it is a requirement of the underlying EML validator that all `@id` fields and the `@packageId` field be unique. I don't understand why this happens for this dataset but not for others. Can you clarify the sequence of events that leads to those two fields being set to the same value on this dataset but not on others?

**Comment by vchendrix** [comment] 2022-07-13 23:31
> @vchendrix You say that "The problem is that `eml.packageId` and `eml.dataset.id` are the same", but that has always been the case -- it is a requirement of the underlying EML validator that all `@id` fields and the `@packageId` field be unique. I don't understand why this happens for this dataset but not for others. Can you clarify the sequence of events that leads to those two fields being set to the same value on this dataset but not on others?

@mbjones Happy to explain further.  When there are annotations the `dataset` element needs an id.  Metacatui places an _xml safe_ id in which  all colons are converted to hyphens. So the packageId ends up being `urn:uuid:e727256e-e3ce-42d6-a932-1acada618b9c` while dataset.id is `urn-uuid-e727256e-e3ce-42d6-a932-1acada618b9c` (See actual eml snippet produced by `EML211.serialize` inside of `EML211.save` from the default metacatui theme)

```xml
<?xml version="1.0"?>
<eml:eml xmlns:eml="https://eml.ecoinformatics.org/eml-2.2.0" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:stmml="http://www.xml-cml.org/schema/stmml-1.1" 
packageId="urn:uuid:e727256e-e3ce-42d6-a932-1acada618b9c" system="ess-dive" xsi:schemaLocation="https://eml.ecoinformatics.org/eml-2.2.0 https://eml.ecoinformatics.org/eml-2.2.0/eml.xsd">    

<dataset id="urn-uuid-e727256e-e3ce-42d6-a932-1acada618b9c">
...
```

However, the ess-dive theme's identifiers are already _xml safe_ and do not produce a different id and thus `eml.packageId` and `eml.dataset.id` are the same which causes this error.

I submitted a solution that utilizes and existing function in `EML211` for generating a unique entity id.

```diff
        //Since there is at least one annotation, the dataset node needs to have an id attribute.
-        datasetNode.attr("id", this.getXMLSafeID());
+       datasetNode.attr("id", this.getUniqueEntityId(this));
```

**Comment by laurenwalker** [comment] 2022-07-14 18:53
This solution looks good to me. Merged to `develop`. I will be releasing a 2.X release next week with these changes along with your other PRs.

**Closed by laurenwalker** 2022-07-14 18:53 UTC
Labels: bug
