### ISSUE TITLE
Derived object icons not being assigned to correct program icon

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#105] opened 2017-05-01 18:12 UTC
A single source object can be used by multiple programs, with each program having it's own
set of outputs. For this case, the derived object icons aren't being displayed with the proper
program icon. For example, for `evosArchResults.csv`, each program that used this file should
have only 1 output file, but the first program displayed is 'greedy' and gets them all:

![image](https://cloud.githubusercontent.com/assets/6412946/25588645/f15235ee-2e5d-11e7-8cc6-12506aa4ce96.png)

Btw, the detail view for each program is correct, with only one output associated with the program:

<img width="990" alt="screen shot 2017-05-01 at 11 05 22 am" src="https://cloud.githubusercontent.com/assets/6412946/25588803/bcc6142a-2e5e-11e7-8042-aea4edb5579b.png">
<img width="952" alt="screen shot 2017-05-01 at 11 12 01 am" src="https://cloud.githubusercontent.com/assets/6412946/25588885/16029afe-2e5f-11e7-82fb-33a6e84ba8cf.png">

**Comment by laurenwalker** [comment] 2018-05-24 20:35
This is a duplicate of #449, just worded in a different way. Will close this issue.

**Closed by laurenwalker** 2018-05-24 20:35 UTC
Labels: bug, provenance
