### ISSUE TITLE
Allow users to update the members tab

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/metacatui#1848] opened 2021-08-11 16:44 UTC
Some portals like DBO have a [members tab](https://arcticdata.io/catalog/portals/DBO/Members) created for them but no way to update the page if it goes out of date through the UI. Right now members of the team will have to go in and help edit that page on their behalf. It is confusing to users who see the page in their portal but when they go into the edit mode the page is not available for edit.

Related to #1739

**Comment by laurenwalker** [comment] 2021-08-12 16:44
Thanks Jasmine. Closing as this is a duplicate of #1131

**Closed by laurenwalker** 2021-08-12 16:44 UTC
Labels: enhancement
