### ISSUE TITLE
Interface for accessing different structured citation formats

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#1608] opened 2020-11-19 20:52 UTC
**Describe the feature you'd like**
In order to support different bibliography tools used be researchers, it would be nice to provide an interface for accessing different structured citation formats (bitex etc) 

**Is your feature request related to a problem? Please describe.**
It is difficult to ingest text citations into bibiliography databases.

**Comment by mbjones** [comment] 2020-11-19 22:44
I think this would be covered by and is highly related to an earlier ticker #973 to support different CSL styles, including export in bibtex format. @rushirajnenuji this has been in your court. @vchendrix do you think the proposal in #973 would work for your case?

**Comment by rushirajnenuji** [comment] 2020-11-20 18:23
Hi @mbjones  - yes, this was on the back burner for a while. I noticed that Lauren bumped this issue to the next pipeline. I'll actively start working on this.

**Comment by laurenwalker** [comment] 2021-01-12 19:58
Closing as it sounds like a duplicate of #973. We can reopen if there's clarification on how it's different. Thanks

**Closed by laurenwalker** 2021-01-12 19:58 UTC
Labels: ESS-DIVE, enhancement, metrics-display
