### ISSUE TITLE
add portal page type for data submission pass through

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#1070] opened 2019-08-22 21:56 UTC
At DataONE, a strong use case emerged for DataONE-deployed portals to be able to be configured to include a MetacatUI-based data submission and editing form.  The concept is to provide a place for data submissions from DataONE portals that get passed through to one of the member repositories in DataONE such as KNB or ADC or others.  This is dependent upon 1) the target repo supporting the Tier 3 API, and also supporting the type of content to be submitted (EML metadata and data types initially).

We can see two deployment scenarios:

- deploy portal that gives the user a dropdown list of submission targets
- deploy portal that is tied directly to one backend repository (e.g., KNB)

Both of these give a targeted user community a way to submit to a particular repository.  They also provide an opportunity for the submission form to be customized for the particular portal, which should include features like:

- ability to set default metadata fields through a "template" metadata document
- ability to constrain choices in specific metadata fields to a specific controlled vocabulary
    - example 1: choose from a pre-configured site list for geographic descriptions
    - example 2: add an annotation field to tie a dataset to a controlled vocab of sampling locations
    - example 3: add one or more controlled keywords from a specific vocabulary either to the keyword set or an annotation field

Let's discuss approaches and details and figure out how this fits into the implementation plans.

**Comment by robyngit** [comment] 2023-05-17 20:40
Duplicate of #1382. Copied details here over to that issue.

**Closed by robyngit** 2023-05-17 20:40 UTC
Labels: Portal Editor
