### ISSUE TITLE
Make the tab titles on the dataset pages specific to the dataset rather than “Arctic Data Center” for all datasets

### ISSUE THREAD

**Issue by erinlynmclean** [NCEAS/metacatui#1750] opened 2021-05-13 16:46 UTC
**Describe the feature you'd like**
Make the tab titles on the dataset pages specific to the dataset rather than “Arctic Data Center” for all datasets

**Additional context**
Requested from the portals focus groups

**Comment by laurenwalker** [comment] 2021-05-18 18:04
Duplicate of #1723

**Closed by laurenwalker** 2021-05-18 18:04 UTC
Labels: enhancement, portals, portals focus group
