### ISSUE TITLE
display `distribution` element at the `dataset` level

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#1917] opened 2021-11-18 19:54 UTC
**Describe the feature you'd like**
The distribution element is sometimes used to specify where exactly a dataset can be downloaded from. This is particularly relevant if data are hosted elsewhere. It would be nice to display this top level distribution element if it exists.

**Additional context**

On the Arctic Data Center we could make particular use of this for data hosted outside of metacat, whether that is on a separate repository or on the data/ pages. 

related to #1380

**Comment by amoeba** [comment] 2021-11-18 21:26
Thanks for filing, @jeanetteclark. I think this would be broadly useful.

We have a mirror ticket for this over on https://github.com/NCEAS/metacat/issues/1241 which I mention just so the two are linked. The real work would happen over there but I think we can leave this ticket open for tracking purposes.

**Comment by laurenwalker** [comment] 2021-12-20 15:14
I'm going to close as a duplicate of the metacat issue linked above

**Closed by laurenwalker** 2021-12-20 15:14 UTC
Labels: enhancement
